AWSTemplateFormatVersion: "2010-09-09"

Description: "AWS CloudFormation Template to create an EC2 instance"

Resources:
  EC2Instance:
    Type: "AWS::EC2::Instance"
    Properties:
      InstanceType: "t2.micro"
      ImageId: "ami-0b995c42184e99f98"
      SecurityGroups:
        - Ref: "SecurityGroup"

  SecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: "Enable SSH access"
      SecurityGroupIngress:
        - IpProtocol: "tcp"
          FromPort: "22"
          ToPort: "22"
          CidrIp: "0.0.0.0/0"


# NOTE: Template validated
# aws cloudformation validate-template --template-body file://main.yml
#Description: AWS CloudFormation Template to create an EC2 instance
#Parameters: []